package productcapability

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

// MessagesCapability implements product.messages.v1
type MessagesCapability struct {
	db *sql.DB
}

func NewMessagesCapability(db *sql.DB) *MessagesCapability {
	return &MessagesCapability{db: db}
}

func (c *MessagesCapability) DescriptorID() string {
	return "product.messages.v1"
}

func (c *MessagesCapability) HandleRead(ctx context.Context, operation string, input []byte) ([]byte, error) {
	switch operation {
	case "list":
		return c.listMessages(ctx, input)
	default:
		return nil, ErrOperationNotFound
	}
}

func (c *MessagesCapability) HandleMutation(ctx context.Context, operation string, input []byte) ([]byte, error) {
	switch operation {
	case "send":
		return c.sendMessage(ctx, input)
	default:
		return nil, ErrOperationNotFound
	}
}

type Message struct {
	EventID   string    `json:"event_id"`
	RoomID    string    `json:"room_id"`
	Sender    string    `json:"sender"`
	Type      string    `json:"type"`
	Content   string    `json:"content"`
	Timestamp time.Time `json:"timestamp"`
}

func (c *MessagesCapability) listMessages(ctx context.Context, input []byte) ([]byte, error) {
	var req struct {
		RoomID string `json:"room_id"`
		Limit  int    `json:"limit"`
		Before string `json:"before"` // event_id to paginate before
	}
	if err := json.Unmarshal(input, &req); err != nil {
		return nil, err
	}

	if req.Limit <= 0 {
		req.Limit = 50
	}

	// Query recent messages from syncapi_output_room_events
	var query string
	var args []interface{}

	if req.Before != "" {
		// Paginate before a specific event
		query = `
			SELECT event_id, room_id, sender, type, headered_event_json, id
			FROM syncapi_output_room_events
			WHERE room_id = $1 AND id < (SELECT id FROM syncapi_output_room_events WHERE event_id = $2)
			ORDER BY id DESC
			LIMIT $3
		`
		args = []interface{}{req.RoomID, req.Before, req.Limit}
	} else {
		// Get most recent messages
		query = `
			SELECT event_id, room_id, sender, type, headered_event_json, id
			FROM syncapi_output_room_events
			WHERE room_id = $1
			ORDER BY id DESC
			LIMIT $2
		`
		args = []interface{}{req.RoomID, req.Limit}
	}

	rows, err := c.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var messages []*Message
	for rows.Next() {
		msg := &Message{}
		var eventJSON string
		var streamID int64
		err := rows.Scan(&msg.EventID, &msg.RoomID, &msg.Sender, &msg.Type, &eventJSON, &streamID)
		if err != nil {
			return nil, err
		}
		// Store the full event JSON as content for now
		msg.Content = eventJSON
		messages = append(messages, msg)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return json.Marshal(map[string]interface{}{
		"messages": messages,
		"total":    len(messages),
	})
}

func (c *MessagesCapability) sendMessage(ctx context.Context, input []byte) ([]byte, error) {
	var req struct {
		RoomID  string                 `json:"room_id"`
		Sender  string                 `json:"sender"`
		Type    string                 `json:"type"`
		Content map[string]interface{} `json:"content"`
	}
	if err := json.Unmarshal(input, &req); err != nil {
		return nil, err
	}

	// TODO: This would need to integrate with the Matrix roomserver to actually send messages
	// For now, return a placeholder response
	// In production, this should call the roomserver API to create and send the event

	return json.Marshal(map[string]interface{}{
		"event_id":  "", // Would be generated by roomserver
		"room_id":   req.RoomID,
		"sender":    req.Sender,
		"type":      req.Type,
		"timestamp": time.Now(),
		"note":      "Message sending requires roomserver integration",
	})
}
