package executionplanning

// This file is the trusted plan-seal boundary for the first generic AWS SSM
// service slice. Typed steps retain their product meaning; deterministic shell
// artifacts are derived once, stored content-addressably, and digest-bound to
// the immutable plan. The runtime may execute only those exact artifacts.

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net"
	"net/url"
	"regexp"
	"sort"
	"strings"

	"github.com/YingSuiAI/dirextalk-message-server/p2p/internal/agentcontrol/artifactstore"
	coreaws "github.com/YingSuiAI/dirextalk-message-server/p2p/internal/agentcontrol/aws"
	coreexecution "github.com/YingSuiAI/dirextalk-message-server/p2p/internal/agentcontrol/execution"
	"github.com/google/uuid"
)

var ErrExecutorSeal = errors.New("execution planning: executor artifact seal failed")

const executorArtifactMediaType = "application/x-sh"

var executorNamePattern = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,127}$`)

type executorContentStore interface {
	Put(context.Context, io.Reader, artifactstore.PutOptions) (artifactstore.Metadata, error)
}

type ExecutorSealRequest struct {
	OwnerID      string
	ProjectID    string
	PlanID       string
	PlanRevision uint64
	Observation  coreexecution.TargetObservationRef
	Stages       []coreexecution.ExecutionStage
}

type ExecutorSealResult struct {
	Stages    []coreexecution.ExecutionStage
	Artifacts []coreexecution.ArtifactRef
}

type ExecutorSealer interface {
	SealExecutors(context.Context, ExecutorSealRequest) (ExecutorSealResult, error)
}

// ArtifactExecutorSealer publishes only deterministic artifacts generated by
// this package. It never accepts command bytes or templates from a client.
type ArtifactExecutorSealer struct{ store executorContentStore }

func NewArtifactExecutorSealer(store *artifactstore.Store) *ArtifactExecutorSealer {
	if store == nil {
		return nil
	}
	return &ArtifactExecutorSealer{store: store}
}

func (s *ArtifactExecutorSealer) SealExecutors(ctx context.Context, in ExecutorSealRequest) (ExecutorSealResult, error) {
	var out ExecutorSealResult
	if s == nil || s.store == nil || strings.TrimSpace(in.OwnerID) == "" || !coreexecution.ValidateUUID(in.ProjectID) || !coreexecution.ValidateUUID(in.PlanID) || in.PlanRevision == 0 {
		return out, ErrExecutorSeal
	}
	observation, err := in.Observation.Normalize()
	observationReady := err == nil

	removed := map[string]bool{}
	containerNames := map[string]bool{}
	for _, stage := range in.Stages {
		if observationReady && isObservationPrerequisite(stage, observation) {
			removed[stage.StageKey] = true
			continue
		}
		for _, step := range stage.Steps {
			if step.ContainerApply != nil {
				containerNames[step.ContainerApply.Name] = true
			}
		}
	}

	for _, sourceStage := range in.Stages {
		if removed[sourceStage.StageKey] {
			continue
		}
		stage := sourceStage
		stage.DependsOn = withoutRemovedDependencies(stage.DependsOn, removed)
		stage.Digest = ""
		stage.Steps = append([]coreexecution.ExecutionStep(nil), sourceStage.Steps...)
		stage.RollbackSteps = append([]coreexecution.ExecutionStep(nil), sourceStage.RollbackSteps...)
		for i := range stage.Steps {
			artifact, sealErr := s.sealStep(ctx, in, stage.StageKey, coreexecution.StepSetForward, &stage.Steps[i], observation, containerNames)
			if sealErr != nil {
				return ExecutorSealResult{}, sealErr
			}
			if artifact.ID != "" {
				out.Artifacts = append(out.Artifacts, artifact)
			}
		}
		for i := range stage.RollbackSteps {
			artifact, sealErr := s.sealStep(ctx, in, stage.StageKey, coreexecution.StepSetRollback, &stage.RollbackSteps[i], observation, containerNames)
			if sealErr != nil {
				return ExecutorSealResult{}, sealErr
			}
			if artifact.ID != "" {
				out.Artifacts = append(out.Artifacts, artifact)
			}
		}
		if needsPrivilegedEffect(stage.Steps) && stage.Risk == coreexecution.RiskR2 {
			if stage.Gate != coreexecution.GateRemotePrivilegedExecution {
				return ExecutorSealResult{}, ErrExecutorSeal
			}
			stage.Effects = appendGate(stage.Effects, coreexecution.GateRemotePrivilegedExecution)
		}
		out.Stages = append(out.Stages, stage)
	}
	if len(out.Stages) == 0 {
		return ExecutorSealResult{}, ErrExecutorSeal
	}
	sort.Slice(out.Artifacts, func(i, j int) bool { return out.Artifacts[i].ID < out.Artifacts[j].ID })
	return out, nil
}

func (s *ArtifactExecutorSealer) sealStep(ctx context.Context, in ExecutorSealRequest, stageKey string, set coreexecution.StepSet, step *coreexecution.ExecutionStep, observation coreexecution.TargetObservationRef, containerNames map[string]bool) (coreexecution.ArtifactRef, error) {
	if step == nil || step.Executor != nil {
		return coreexecution.ArtifactRef{}, ErrExecutorSeal
	}
	// Authorization control steps are typed provider inputs, not shell
	// artifacts. They are sealed by strict payload validation and remain
	// non-executable until the dedicated coordinator/runtime handles them.
	if step.Kind == coreexecution.StepSecretProvision || step.Kind == coreexecution.StepExternalAuth {
		if step.TargetID != observation.TargetID || step.TargetRevision != observation.TargetRevision || step.TargetDigest == "" || step.ObservationRef != nil || len(step.ArtifactRefs) != 0 || len(step.Permissions) != 0 || len(step.NetworkGrants) != 0 || step.Postcondition != nil || step.OutputPolicy != coreexecution.OutputDiscard || step.OutputKey != "" || step.TimeoutSeconds == 0 || step.IdempotencyMarker == "" {
			return coreexecution.ArtifactRef{}, ErrExecutorSeal
		}
		switch step.Kind {
		case coreexecution.StepSecretProvision:
			if step.SecretProvision == nil || step.SecretProvision.Delivery != "target_secure_parameter" || len(step.SecretRefs) != 1 || !validAISecretRef(step.SecretRefs[0]) {
				return coreexecution.ArtifactRef{}, ErrExecutorSeal
			}
		case coreexecution.StepExternalAuth:
			if step.ExternalAuth == nil || step.ExternalAuth.Provider == "" || step.ExternalAuth.Status != coreexecution.AIExternalAuthPending || len(step.SecretRefs) != 0 {
				return coreexecution.ArtifactRef{}, ErrExecutorSeal
			}
		}
		return coreexecution.ArtifactRef{}, nil
	}
	if step.Kind == coreexecution.StepComputeProvision {
		if step.ComputeProvision == nil || step.ObservationRef != nil || len(step.ArtifactRefs) != 0 || len(step.NetworkGrants) != 0 || len(step.SecretRefs) != 0 || len(step.Permissions) != 0 || step.Postcondition != nil || step.OutputPolicy != "" || step.OutputKey != "" {
			return coreexecution.ArtifactRef{}, ErrExecutorSeal
		}
		return coreexecution.ArtifactRef{}, nil
	}
	if step.TargetID != observation.TargetID || step.TargetRevision != observation.TargetRevision {
		return coreexecution.ArtifactRef{}, ErrExecutorSeal
	}
	var script []byte
	var root bool
	var err error
	switch step.Kind {
	case coreexecution.StepPackageEnsure:
		script, root, err = packageEnsureScript(step)
	case coreexecution.StepContainerApply:
		script, root, err = containerApplyScript(step)
	case coreexecution.StepHTTPProbe:
		script, root, err = httpProbeScript(step)
	case coreexecution.StepCleanup:
		script, root, err = cleanupScript(step, containerNames)
	case coreexecution.StepScriptRun:
		// script.run already carries an immutable, fully constrained artifact.
		return coreexecution.ArtifactRef{}, nil
	default:
		return coreexecution.ArtifactRef{}, fmt.Errorf("%w: unsupported step kind %s", ErrExecutorSeal, step.Kind)
	}
	if err != nil || len(script) == 0 {
		return coreexecution.ArtifactRef{}, ErrExecutorSeal
	}
	sum := sha256.Sum256(script)
	digest := hex.EncodeToString(sum[:])
	size := int64(len(script))
	meta, err := s.store.Put(ctx, bytes.NewReader(script), artifactstore.PutOptions{ExpectedDigest: digest, ExpectedSize: &size, MaxSize: 1 << 20})
	if err != nil || meta.Digest != digest || meta.Size != size {
		return coreexecution.ArtifactRef{}, ErrExecutorSeal
	}
	namespace, err := uuid.Parse(in.PlanID)
	if err != nil {
		return coreexecution.ArtifactRef{}, ErrExecutorSeal
	}
	artifactID := uuid.NewSHA1(namespace, []byte(fmt.Sprintf("executor/v2:%d:%s:%s:%s:%s", in.PlanRevision, stageKey, set, step.StepKey, digest))).String()
	artifact := coreexecution.ArtifactRef{ID: artifactID, Digest: coreexecution.Digest(digest), MediaType: executorArtifactMediaType, Size: size, Immutable: true}
	post := &coreexecution.Postcondition{Type: "exit_code", Value: "0"}
	step.ObservationRef = &observation
	step.OutputPolicy = coreexecution.OutputDiscard
	step.Postcondition = post
	step.Digest = ""
	step.Executor = &coreexecution.ExecutorSpec{
		Artifact: artifact, Interpreter: "/bin/sh", CWD: "/", Root: root,
		AllowedExitCodes: []int{0}, OutputLimit: 4096, Postcondition: post,
	}
	return artifact, nil
}

func validAISecretRef(ref coreexecution.CredentialRef) bool {
	return coreexecution.ValidateUUID(ref.Ref) && ref.Purpose == coreexecution.AISecretPurposeProviderAPIKey && ref.Revision > 0 && ref.BindingDigest.Valid()
}

func isObservationPrerequisite(stage coreexecution.ExecutionStage, observation coreexecution.TargetObservationRef) bool {
	if len(stage.Steps) == 0 || len(stage.RollbackSteps) != 0 || stage.Risk != coreexecution.RiskR0 || stage.Gate != coreexecution.GateNone || stage.TargetID != observation.TargetID || stage.TargetRevision != observation.TargetRevision {
		return false
	}
	for _, step := range stage.Steps {
		if step.Kind != coreexecution.StepTargetInspect || step.TargetInspect == nil || step.TargetInspect.ObservationID != observation.ObservationID {
			return false
		}
	}
	return true
}

func withoutRemovedDependencies(in []string, removed map[string]bool) []string {
	out := make([]string, 0, len(in))
	for _, dependency := range in {
		if !removed[dependency] {
			out = append(out, dependency)
		}
	}
	return out
}

func needsPrivilegedEffect(steps []coreexecution.ExecutionStep) bool {
	for _, step := range steps {
		if step.Executor != nil && step.Executor.Root {
			return true
		}
	}
	return false
}

func appendGate(in []coreexecution.Gate, want coreexecution.Gate) []coreexecution.Gate {
	for _, gate := range in {
		if gate == want {
			return in
		}
	}
	out := append(append([]coreexecution.Gate(nil), in...), want)
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func packageEnsureScript(step *coreexecution.ExecutionStep) ([]byte, bool, error) {
	if step.PackageEnsure == nil || step.PackageEnsure.Name != "docker" || step.PackageEnsure.Version != "" || step.PackageEnsure.Manager != "dnf" || step.PackageEnsure.PlatformProfile != "amazon-linux-2023" || len(step.NetworkGrants) != 1 || len(step.SecretRefs) != 0 {
		return nil, false, ErrExecutorSeal
	}
	grant, err := step.NetworkGrants[0].Normalize()
	if err != nil || grant.Scope != "external" || grant.Scheme != "https" || grant.Host != coreexecution.PublicHTTPSWildcardHost || grant.Port != 443 || grant.PathPrefix != "" {
		return nil, false, ErrExecutorSeal
	}
	return []byte("#!/bin/sh\nset -eu\n. /etc/os-release\n[ \"${ID:-}\" = amzn ]\ncase \"${VERSION_ID:-}\" in 2023*) ;; *) exit 65 ;; esac\nif ! command -v docker >/dev/null 2>&1; then command -v dnf >/dev/null 2>&1; dnf install -y docker; fi\nsystemctl enable --now docker >/dev/null\ndocker version >/dev/null 2>&1\n"), true, nil
}

func containerApplyScript(step *coreexecution.ExecutionStep) ([]byte, bool, error) {
	if step.ContainerApply == nil || len(step.SecretRefs) > 1 || !executorNamePattern.MatchString(step.ContainerApply.Name) || step.ContainerApply.HostAddress != "127.0.0.1" || step.ContainerApply.HostPort < 1 || step.ContainerApply.HostPort > 65535 || step.ContainerApply.ContainerPort < 1 || step.ContainerApply.ContainerPort > 65535 || step.ContainerApply.RestartPolicy != "unless-stopped" {
		return nil, false, ErrExecutorSeal
	}
	for _, ref := range step.SecretRefs {
		if ref.Purpose != coreaws.ExecutionSecretPurposeAIProviderAPIKey || !coreexecution.ValidateUUID(ref.Ref) || ref.Revision == 0 || !ref.BindingDigest.Valid() {
			return nil, false, ErrExecutorSeal
		}
	}
	_, _, err := pinnedImageRegistry(step.ContainerApply.Image)
	if err != nil || len(step.NetworkGrants) != 1 {
		return nil, false, ErrExecutorSeal
	}
	grant, err := step.NetworkGrants[0].Normalize()
	if err != nil || grant.Scope != "external" || grant.Scheme != "https" || grant.Host != coreexecution.PublicHTTPSWildcardHost || grant.Port != 443 || grant.PathPrefix != "" {
		return nil, false, ErrExecutorSeal
	}
	specDigest, err := coreexecution.CanonicalDigest(struct {
		Container coreexecution.ContainerApplyStep
		Secrets   []coreexecution.CredentialRef
	}{*step.ContainerApply, append([]coreexecution.CredentialRef(nil), step.SecretRefs...)})
	if err != nil {
		return nil, false, ErrExecutorSeal
	}
	image, name := executorShellQuote(step.ContainerApply.Image), executorShellQuote(step.ContainerApply.Name)
	label := executorShellQuote(string(specDigest))
	port := fmt.Sprintf("%s:%d:%d", step.ContainerApply.HostAddress, step.ContainerApply.HostPort, step.ContainerApply.ContainerPort)
	secretSetup := "[ \"$#\" -eq 0 ] || exit 64\n"
	secretMount := ""
	secretCommit := ""
	if len(step.SecretRefs) == 1 {
		purpose := step.SecretRefs[0].Purpose
		hostDirectory := "/run/dirextalk/secrets/" + step.ContainerApply.Name
		secretSetup = "[ \"$#\" -eq 1 ] || exit 64\n" +
			"command -v aws >/dev/null 2>&1\n" +
			"secret_dir=" + executorShellQuote(hostDirectory) + "\n" +
			"install -d -m 0700 -- \"$secret_dir\"\n" +
			"tmp=$(mktemp \"$secret_dir/." + purpose + ".XXXXXX\") || exit 125\n" +
			"trap 'rm -f -- \"$tmp\"' EXIT\n" +
			"AWS_PAGER='' aws ssm get-parameter --name \"$1\" --with-decryption --query Parameter.Value --output text > \"$tmp\"\n" +
			"truncate -s -1 \"$tmp\"\n" +
			"test -s \"$tmp\"\n" +
			"chmod 0400 \"$tmp\"\n" +
			"secret_file=\"$secret_dir/" + purpose + "\"\n" +
			"mv -f -- \"$tmp\" \"$secret_file\"\n" +
			"trap 'rm -f -- \"$secret_file\"' EXIT\n"
		secretMount = " --mount " + executorShellQuote("type=bind,src="+hostDirectory+",dst=/run/secrets/dirextalk,readonly")
		secretCommit = "trap - EXIT\n"
	}
	script := "#!/bin/sh\nset -eu\n" +
		"command -v docker >/dev/null 2>&1\n" +
		"docker pull " + image + " >/dev/null\n" +
		"existing=0\n" +
		"if docker container inspect " + name + " >/dev/null 2>&1; then\n" +
		"  current=$(docker inspect --format '{{ index .Config.Labels \"io.dirextalk.execution-spec\" }}' " + name + ")\n" +
		"  if [ \"$current\" != " + label + " ]; then echo 'container exists with a different execution spec; upgrade/repair requires a versioned rollback strategy' >&2; exit 73; fi\n" +
		"  existing=1\n" +
		"fi\n" +
		secretSetup +
		"if [ \"$existing\" -eq 1 ]; then " + secretCommit + "exit 0; fi\n" +
		"docker run -d --name " + name + " --restart unless-stopped --label io.dirextalk.execution-spec=" + label + " -p " + executorShellQuote(port) + secretMount + " " + image + " >/dev/null\n" +
		secretCommit
	return []byte(script), true, nil
}

func httpProbeScript(step *coreexecution.ExecutionStep) ([]byte, bool, error) {
	if step.HTTPProbe == nil || step.HTTPProbe.Mode != "target_local" || len(step.SecretRefs) != 0 || len(step.NetworkGrants) != 1 || len(step.HTTPProbe.ExpectedStatus) == 0 {
		return nil, false, ErrExecutorSeal
	}
	u, err := url.Parse(step.HTTPProbe.URL)
	if err != nil || u.Scheme != "http" || u.Hostname() != "127.0.0.1" || u.User != nil || u.RawQuery != "" || u.Fragment != "" {
		return nil, false, ErrExecutorSeal
	}
	port := u.Port()
	if port == "" {
		port = "80"
	}
	grant, err := step.NetworkGrants[0].Normalize()
	if err != nil || grant.Scope != "target_local" || grant.Scheme != "http" || grant.Host != "127.0.0.1" || fmt.Sprint(grant.Port) != port || grant.PathPrefix != u.EscapedPath() && grant.PathPrefix != u.Path {
		return nil, false, ErrExecutorSeal
	}
	statuses := append([]int(nil), step.HTTPProbe.ExpectedStatus...)
	sort.Ints(statuses)
	cases := make([]string, 0, len(statuses))
	for _, status := range statuses {
		if status < 100 || status > 599 {
			return nil, false, ErrExecutorSeal
		}
		cases = append(cases, fmt.Sprint(status))
	}
	script := "#!/bin/sh\nset -eu\ncommand -v curl >/dev/null 2>&1\ncode=$(curl --silent --show-error --output /dev/null --max-time 20 --write-out '%{http_code}' " + executorShellQuote(step.HTTPProbe.URL) + ")\ncase \"$code\" in\n  " + strings.Join(cases, "|") + ") exit 0 ;;\n  *) exit 22 ;;\nesac\n"
	return []byte(script), false, nil
}

func cleanupScript(step *coreexecution.ExecutionStep, containerNames map[string]bool) ([]byte, bool, error) {
	if step.Cleanup == nil || len(step.NetworkGrants) != 0 || len(step.SecretRefs) != 0 || !executorNamePattern.MatchString(step.Cleanup.Resource) || !containerNames[step.Cleanup.Resource] {
		return nil, false, ErrExecutorSeal
	}
	name := executorShellQuote(step.Cleanup.Resource)
	secretDirectory := executorShellQuote("/run/dirextalk/secrets/" + step.Cleanup.Resource)
	return []byte("#!/bin/sh\nset -eu\ncommand -v docker >/dev/null 2>&1\nif docker container inspect " + name + " >/dev/null 2>&1; then docker rm -f " + name + " >/dev/null; fi\nrm -rf -- " + secretDirectory + "\n"), true, nil
}

func pinnedImageRegistry(image string) (string, string, error) {
	const marker = "@sha256:"
	i := strings.LastIndex(image, marker)
	if i < 1 || len(image[i+len(marker):]) != 64 || !coreexecution.Digest(image[i+len(marker):]).Valid() {
		return "", "", ErrExecutorSeal
	}
	name := image[:i]
	slash := strings.IndexByte(name, '/')
	if slash < 1 || slash == len(name)-1 {
		return "", "", ErrExecutorSeal
	}
	host, repository := strings.ToLower(name[:slash]), name[slash+1:]
	if strings.ContainsAny(repository, "\r\n\x00") || strings.Contains(repository, "..") || strings.HasPrefix(repository, "/") {
		return "", "", ErrExecutorSeal
	}
	parsed, err := url.Parse("https://" + host + "/" + repository)
	if err != nil || parsed.User != nil || parsed.Hostname() == "" || parsed.Port() != "" && parsed.Port() != "443" {
		return "", "", ErrExecutorSeal
	}
	registry := strings.ToLower(parsed.Hostname())
	if ip := net.ParseIP(registry); ip != nil && (ip.IsLoopback() || ip.IsPrivate() || ip.IsLinkLocalUnicast()) {
		return "", "", ErrExecutorSeal
	}
	if registry == "localhost" || !strings.Contains(registry, ".") {
		return "", "", ErrExecutorSeal
	}
	return registry, repository, nil
}

func executorShellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
